FROM nvcr.io/nvidia/tritonserver:24.08-pyt-python-py3

RUN pip install --no-cache-dir \
    transformers==4.45.2 \
    accelerate==0.34.2 \
    sentencepiece==0.2.0 \
    einops==0.8.0 \
    protobuf==4.25.3